var onionPrice = 20;
var eggPrice = 11;
var totalPrice =onionPrice -eggPrice;
// console.log(totalPrice);
// console.log(onionPrice);
// console.log(eggPrice);
// console.log(onionPrice+eggPrice);
// console.log(onionPrice-eggPrice);
// console.log(eggPrice-onionPrice);
var applePrice = 20 ;
var amount =10;
var totalprice =applePrice*amount;
// console.log(totalprice);
var singlePrice = applePrice / amount;
console.log(singlePrice);